rcc:
  noauths: /,/api/**/*,/index.html,/check,/console/user/login,/user/loginByUuap,/rpc/ExtConfigServerService,/img/**/*,/js/**/*,/css/**/*,/swagger-ui.html,/webjars/**,/v2/**,/swagger-resources/**,/csrf
  user:
    type:
      default: 1
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: NON_NULL
  resources:
    static-locations: classpath:/dist,classpath:/static,classpath:/public,classpath:/resources,classpath:/META-INF/resources
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      allow-pool-suspension: false
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1200000
    name: rcc-datasource
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://${db.host}:${db.port}/brcc?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: ${db.username}
    password: ${db.password}
  redis:
    host: ${redis.host}
    port: ${redis.port}
mybatis:
  configuration:
    default-statement-timeout: 60
  mapper-locations: classpath*:mybatis/**/*.xml
  type-aliases-package: com.baidu.brcc.domain
management:
  endpoints:
    web:
      exposure:
        include: '*'
    jmx:
      exposure:
        include: '*'
  metrics:
    distribution:
      percentiles-histogram.http.server.requests: false

